services:

  db:
    image: mysql
    container_name: mtg-keyword-helper-db
    ports:
      - 3001:3306
    restart: always
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
